### ISSUE TITLE
Improve performance with larger trees

### ISSUE THREAD

**Issue by quantumjot** [lowe-lab-ucl/arboretum#16]
stress test the plotter with larger lineage trees. perhaps consider swapping to vispy for rendering

**Comment by alessandrofelder** [comment]
Can't find it now, but it does ring a bell here too 🤔 - [workshop recordings and slides](https://chanzuckerberg.github.io/napari-plugin-accel-workshops/) if someone else wants to have a deeper look.

**Comment by dstansby** [comment]
I've had a go at this today, code is in https://github.com/lowe-lab-ucl/arboretum/pull/42. Adding a tree with 127 branches is noticably slow to load, and slightly laggy to interact with once loaded 😞 Adding one with 255 branches takes ~5 seconds, and is almost unusable when interacting with it. I'll try and do some profiling this afternoon to work out what the issues are here.

**Comment by quantumjot** [comment]
> noticably slow to load, and slightly laggy

One possibility is to use a single vispy `LineVisual` node to represent the whole tree. I think some of the performance hits may come from creating lots of subvisuals.  Line visuals have the `connect` parameter which can be used to draw non-contiguous line sections:
https://vispy.org/api/vispy.visuals.line.line.html

At any rate, profiling is the way to go!

**Comment by dstansby** [comment]
I had a play this morning, and using a single `LineVisual` does indeed work. It needs careful implementation in `arboretum` though, to track which indices of the position array correspond to which tracks so we can update the colours after the visual has been created. I don't have enough firing brain cells to work that out today 😄 , but it does seem like the right route to go here.

**Comment by dstansby** [comment]
Note from today, at least some of the logic for implementing a single `LineVisual` already lives in the `Tracks` layer of `napari`.

**Comment by dstansby** [comment]
The most expensive thing in terms of performance is drawing a lot of text visuals for the track IDs, so I think the best way to attack this issue is to first think about a strategy for reducing the amount of text drawn for large trees.

**Comment by quantumjot** [comment]
> is drawing a lot of text visuals 

This is good to know! I wonder if we should limit to one text visual per branch, arranged as:

- At the last time point for a terminal leaf
- At the first time point for a root
- In the middle for everything else (e.g. not root/leaf)

What do you think?
