### ISSUE TITLE
Lineage Tree Annotation Offset

### ISSUE THREAD

**Issue by KristinaUlicna** [lowe-lab-ucl/arboretum#75]
[In ~150 frames-long movie with ~15k segmented objects] Some lineage trees appear outside of the window (branch aligned to the left window wall, see pic below). Also, I noticed that some trees don't have the horizontal line showing, until I find a tree that has it shown, and from that moment on all trees show the line - even those that didn't before.

<img width="2560" alt="Screenshot 2022-06-24 at 15 56 56" src="https://user-images.githubusercontent.com/48791041/175562035-93b4dc06-fe49-4a04-8d99-3f4faa0495c6.png">

**Comment by KristinaUlicna** [comment]
I think the single branches only get centred in the window after you find a tree that is branching - if you only click on a cell that isn't a part of a wider tree, the centring is off.

**Comment by KristinaUlicna** [comment]
Also, sometimes the tree doesn't show at all - but I do not see any pattern here..
<img width="2560" alt="Screenshot 2022-06-27 at 15 52 11" src="https://user-images.githubusercontent.com/48791041/176002322-a4ce0b21-e92d-45b7-947d-690231db8970.png">
.

**Comment by quantumjot** [comment]
I've fixed this one in #78 now. The tree not showing at all is related to #68. Working on a fix for that too
