### ISSUE TITLE
Import dependencies

### ISSUE THREAD

**Issue by goanpeca** [lowe-lab-ucl/arboretum#79]
Hi @quantumjot, it seems some explicitly used libraries are not being listed as dependencies.

This includes:
- `qtpy` -> https://github.com/lowe-lab-ucl/arboretum/search?q=qtpy
- `skimage` -> https://github.com/lowe-lab-ucl/arboretum/search?q=skimage

Additionally the library is importing `PyQt5` https://github.com/lowe-lab-ucl/arboretum/search?q=pyqt5 and it should be using `qtpy` instead. More details on why this is recommended can be found in the [napari best practices documentation](https://napari.org/stable/plugins/best_practices.html)

Could you make theses fixes for the next release?

Cheers!

**Comment by quantumjot** [comment]
Great stuff - thanks for looking into this @goanpeca! We'll make sure to fix this for the next release.
