### ISSUE TITLE
Save Tree feature and Nodes labeling 

### ISSUE THREAD

**Issue by Ciro1990** [lowe-lab-ucl/arboretum#81]
Dear all,

First of all, thanks for developing Arboretum. I was wondering if it was possible to add a feature to save the lineage tree visualized. 

Additionally, it would be nice if on the nodes, we could have a small circle with the ID inside, instead of having the ID numbers on the branches.

Thanks!
Ciro

**Comment by quantumjot** [comment]
Hi Ciro - this is a great idea, thanks!

For saving the lineage tree - would it be OK just to save the visualisation itself, kind of like a screenshot, or did you have something else in mind? I know @KristinaUlicna was interested in this feature too.

**Comment by Ciro1990** [comment]
Hi there! Ideally, saving in .svg would be the best option. In this way the trees would have a good quality and the file format would offer the possibility to modify it elsewhere I have tried to save it in .png, but the resolution was too low.

**Comment by quantumjot** [comment]
@Ciro1990 - this PR (#95) should enable basic export to SVG.
