### ISSUE TITLE
lineage tree ignores multiple parents

### ISSUE THREAD

**Issue by will-moore** [lowe-lab-ucl/arboretum#91]
Moved from https://github.com/quantumjot/BayesianTracker/issues/216

With this sample, I have a track that splits into 2 and then they join back into one.

```
viewer = napari.Viewer()
tracks = [
    [0, 1, 50.5, 7.4],
    [0, 2, 50.3, 59.3],
    [1, 3, 73.2, 100.6],
    [1, 4, 75.2, 150.3],
    [2, 3, 13.1, 110.4],
    [2, 4, 14.8, 150.7],
    [3, 5, 54.4, 200.5],
    [3, 6, 52.1, 250.4],
]

graph = {2: [0], 1:[0], 3:[1, 2]}
properties = {"t": [t[1] for t in tracks], "value": [t[3] for t in tracks]}

viewer._add_layer_from_data(tracks, {'graph': graph, 'properties': properties}, "tracks")
napari.run()
```

This shows up correctly on the viewer, but on the lineage tree, the track `3` is shown as only having a single parent:

![Screenshot 2023-03-09 at 09 37 00](https://user-images.githubusercontent.com/900055/223982308-cb96f542-f3cf-4b50-88fc-380452401dbf.png)

Also, the plot at the bottom of the right panel suggests there might be some way to plot the 'properties' of points over time?
Is that right, and if so, how can I get it to show the "value" property in my example?

 Thanks!

**Comment by quantumjot** [comment]
Related https://github.com/lowe-lab-ucl/arboretum/issues/10

**Comment by quantumjot** [comment]
You can change what's plotted using the napari interface on the tracks layer. Just change `color by` to a different property and the tree and property plotter should change to reflect that.

I will take a look at the merges over the next couple of days.

**Comment by quantumjot** [comment]
Hi @will-moore - it looks like #94 will solve this issue:

![merge](https://user-images.githubusercontent.com/8217795/226922695-3229e72b-924e-4349-9152-ebb06be48857.png)

But finding an *optimal* layout for a tree with merges is hard.  I'd be interested to know if it works for your use case?

**Comment by will-moore** [comment]
@quantumjot - Thanks for that:

I'm afraid I don't have data that really requires this feature yet, but I'm writing code that converts tracking data between OME-NGFF tables and napari: https://github.com/ome/napari-ome-zarr/pull/81, so I wanted to test that it would handle splits and merges of tracks, which is how I came across this bug. 

I have a more interesting example with real data from IDR at https://github.com/IDR/idr0113-bottes-opcclones/pull/2, but this still doesn't have merges.
So, apologies if this bug-fix was requested a bit prematurely, but I think/hope it will be useful to "real" use-cases soon. I'll keep a look-out for some.

Thanks for the fix.

**Comment by will-moore** [comment]
More testing:

```
tracks = [
    [0, 1, 50.5, 7.4],
    [0, 2, 50.3, 59.3],
    [1, 3, 73.2, 100.6],
    [1, 4, 75.2, 150.3],
    [2, 3, 13.1, 110.4],
    [2, 4, 14.8, 150.7],
    [3, 5, 54.4, 200.5],
    [3, 6, 52.1, 250.4],
    [4, 5, 50.5, 7.4],
    [4, 6, 50.3, 59.3],
    [5, 5, 73.2, 100.6],
    [5, 6, 75.2, 150.3],
    [6, 5, 13.1, 110.4],
    [6, 6, 14.8, 150.7],
    [7, 7, 54.4, 200.5],
    [7, 8, 52.1, 250.4],
    [8, 7, 54.4, 200.5],
    [8, 8, 52.1, 250.4],
]
graph = {2: [0], 1:[0], 3:[1], 4:[1], 5:[2], 6:[2], 7:[4, 6], 8:[3, 5]}
```
gives:

![Screenshot 2023-03-22 at 17 58 07](https://user-images.githubusercontent.com/900055/226997404-74837dd6-54c8-4ea6-bcaa-679d62220306.png)


But if I try to have a track with track 6 going to tracks 7 *and* 8:
```
graph = {2: [0], 1:[0], 3:[1], 4:[1], 5:[2], 6:[2], 7:[4, 6], 8:[3, 6]}
```
This fails with:
```
File ~/opt/anaconda3/envs/SSBD/lib/python3.9/site-packages/napari_arboretum/tree.py:145, in layout_tree
    142         continue
    144     for child_id in edge.node.children:
--> 145         child_edge = [e for e in edges if e.track_id == child_id][0]

IndexError: list index out of range
```

But please, don't worry about this fake data - It already looks good for "regular" merging of tracks. 👍

**Comment by will-moore** [comment]
Great, thanks!
